# -*- coding: utf-8 -*-
"""RL Code [Hetu's Version]

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HfFgxR4dT_TXttL9DF9x9diwKAuD9G4g
"""

from google.colab import drive
drive.mount('/content/drive')
!tar -xvjf /content/drive/MyDrive/r4.2.tar.bz2 -C /content/drive/MyDrive/

from google.colab import drive
drive.mount('/content/drive')

from google.colab import drive
import os
import shutil

drive.mount('/content/drive')

if not os.path.exists('/content/drive/MyDrive/r4.2'):
    !tar -xjf /content/drive/MyDrive/r4.2.tar.bz2 -C /content/drive/MyDrive/

if not os.path.exists('/content/drive/MyDrive/answers'):
    !tar -xjf /content/drive/MyDrive/answers.tar.bz2 -C /content/drive/MyDrive/

if not os.path.exists('/content/r4.2'):
    shutil.copytree('/content/drive/MyDrive/r4.2', '/content/r4.2')

if not os.path.exists('/content/answers'):
    shutil.copytree('/content/drive/MyDrive/answers', '/content/answers')

DATA_PATH = '/content/r4.2'
ANSWERS_PATH = '/content/answers'

import pandas as pd

answers = pd.read_csv(f"{ANSWERS_PATH}/insiders.csv")
answers.head(20)

answers_df = answers.copy()

colmap = {}
for c in answers_df.columns:
    cl = c.lower().strip()
    if cl in ["user", "userid", "user_id", "employee", "employee_name"]:
        colmap[c] = "user"
    elif cl in ["start", "starttime", "start_time", "begin", "begin_time"]:
        colmap[c] = "start"
    elif cl in ["end", "endtime", "end_time", "stop", "stop_time"]:
        colmap[c] = "end"
    elif cl in ["scenario", "scenario_id", "scenarioid", "type"]:
        colmap[c] = "scenario"

answers_df = answers_df.rename(columns=colmap)
print("Normalized answer columns:", answers_df.columns.tolist())

# Cell 3 — NEW: filter to r4.2 only
# answers_df still has 'dataset' column from the original CSV at this point
answers_df = answers_df[answers_df["dataset"] == 4.2].reset_index(drop=True)

# Now parse dates (only on the filtered rows)
start_raw = answers_df["start"].astype(str)
mask = pd.to_datetime(start_raw, errors="coerce").isna()
answers_df = answers_df[~mask]
answers_df["start"] = pd.to_datetime(answers_df["start"])
answers_df["end"]   = pd.to_datetime(answers_df["end"])

print(f"Insiders after filtering to r4.2 : {len(answers_df)}")
print(f"Unique malicious users           : {answers_df['user'].nunique()}")
print(f"\nScenario breakdown:")
print(answers_df["scenario"].value_counts())
print(f"\nDate range: {answers_df['start'].min().date()} → {answers_df['end'].max().date()}")

start_raw = answers_df["start"].astype(str)

mask = pd.to_datetime(
    start_raw,
    errors="coerce"
).isna()

answers_df.loc[mask, ["start"]]
answers_df = answers_df[~mask]
answers_df["start"] = pd.to_datetime(answers_df["start"])
answers_df["end"] = pd.to_datetime(answers_df["end"])

logon = pd.read_csv("/content/drive/MyDrive/r4.2/logon.csv")
device_df = pd.read_csv("/content/drive/MyDrive/r4.2/device.csv")
for df in [logon, device_df]:
    df['date'] = pd.to_datetime(df['date'])
    df['hour'] = df['date'].dt.floor('h')
file_reader = pd.read_csv("/content/drive/MyDrive/r4.2/file.csv", chunksize=100000)
email_reader = pd.read_csv("/content/drive/MyDrive/r4.2/email.csv", chunksize=100000)
http_reader = pd.read_csv("/content/drive/MyDrive/r4.2/http.csv", chunksize=100000)

chunk = next(pd.read_csv("/content/drive/MyDrive/r4.2/email.csv", chunksize=5))
print(chunk.columns)
print(chunk.head())

import re
chunk = next(pd.read_csv("/content/drive/MyDrive/r4.2/email.csv", chunksize=1000))

# combine recipient fields safely
to_col = chunk["to"].astype(str) if "to" in chunk.columns else ""
cc_col = chunk["cc"].astype(str) if "cc" in chunk.columns else ""
bcc_col = chunk["bcc"].astype(str) if "bcc" in chunk.columns else ""

recipient_text = to_col + ";" + cc_col + ";" + bcc_col

def has_external(recipient_text, internal_domain="dtaa.com"):
    domains = re.findall(r'@([A-Za-z0-9.-]+)', str(recipient_text))
    return any(not d.endswith(internal_domain) for d in domains)

chunk["external_email"] = recipient_text.apply(has_external).astype(int)
domains = recipient_text.str.extractall(r'@([A-Za-z0-9.-]+)')[0]
print(domains.value_counts().head(20))

def aggregate_counts(reader, event_name):
    parts = []

    for chunk in reader:
        chunk["date"] = pd.to_datetime(chunk["date"])
        chunk["hour"] = chunk["date"].dt.floor("h")
        grouped = chunk.groupby(["user", "hour"]).size().reset_index(name=event_name)
        parts.append(grouped)

    result = pd.concat(parts, ignore_index=True)
    result = result.groupby(["user", "hour"], as_index=False)[event_name].sum()
    return result

logon_count = logon.groupby(["user", "hour"]).size().reset_index(name="logon_count")
device_df["usb_used"] = device_df["activity"].astype(str).str.contains("Connect", case=False, na=False).astype(int)
usb_usage = device_df.groupby(["user", "hour"])["usb_used"].max().reset_index()

file_count = aggregate_counts(file_reader, "file_count")
http_count = aggregate_counts(http_reader, "http_count")

def aggregate_email_features(reader, internal_domain="dtaa.com"):
    parts = []

    for chunk in reader:
        chunk["date"] = pd.to_datetime(chunk["date"])
        chunk["hour"] = chunk["date"].dt.floor("h")

        empty = pd.Series("", index=chunk.index)

        to_col = chunk["to"].astype(str) if "to" in chunk.columns else empty
        cc_col = chunk["cc"].astype(str) if "cc" in chunk.columns else empty
        bcc_col = chunk["bcc"].astype(str) if "bcc" in chunk.columns else empty

        recipient_text = to_col + " " + cc_col + " " + bcc_col

        chunk["external_email"] = recipient_text.apply(
            lambda x: has_external(x, internal_domain)
        ).astype(int)

        grouped = chunk.groupby(["user", "hour"]).agg(
            email_count=("user", "size"),
            external_email_count=("external_email", "sum"),
        ).reset_index()

        parts.append(grouped)

    result = pd.concat(parts, ignore_index=True)
    result = result.groupby(["user", "hour"], as_index=False).sum()
    return result

email_features = aggregate_email_features(email_reader)

from functools import reduce
import numpy as np

# ── Step 1: Merge — start from file_count so users with no logon/device events are kept ──
dfs = [file_count, logon_count, usb_usage, email_features, http_count]
incidents = reduce(lambda l, r: pd.merge(l, r, on=["user", "hour"], how="outer"), dfs)
incidents = incidents.fillna(0)

# ── Step 2: Time features (must happen before burst/z-score which depend on counts) ──
incidents["hour"] = pd.to_datetime(incidents["hour"])
incidents["hour_of_day"] = incidents["hour"].dt.hour
incidents["after_hours"] = (
    (incidents["hour_of_day"] < 8) | (incidents["hour_of_day"] > 18)
).astype(int)

# ── Step 3: Sort before any per-user operations ──
incidents = incidents.sort_values(["user", "hour"]).reset_index(drop=True)

# ── Step 4: Burst features (needed BEFORE labeling so we can use them in label filter) ──
incidents["file_burst"]           = (incidents["file_count"]           >= 20).astype(np.float32)
incidents["email_burst"]          = (incidents["email_count"]          >= 15).astype(np.float32)
incidents["http_burst"]           = (incidents["http_count"]           >= 30).astype(np.float32)
incidents["external_email_burst"] = (incidents["external_email_count"] >=  3).astype(np.float32)

# ── Step 5: Per-user z-score features ──
for col in ["logon_count", "file_count", "email_count", "http_count", "external_email_count"]:
    user_mean = incidents.groupby("user")[col].transform("mean")
    user_std  = incidents.groupby("user")[col].transform("std").fillna(0.0)
    incidents[f"{col}_z"] = (
        (incidents[col] - user_mean) / user_std.replace(0, 1.0)
    ).clip(-5, 5).fillna(0.0).astype(np.float32)

# ── Step 6: Rare after-hours ──
user_after_hours_rate = incidents.groupby("user")["after_hours"].transform("mean")
incidents["rare_after_hours"] = (
    (incidents["after_hours"] == 1) & (user_after_hours_rate < 0.10)
).astype(np.float32)

# ── Step 7: Interaction features ──
incidents["usb_after_hours"]         = (incidents["usb_used"]   * incidents["after_hours"]          ).astype(np.float32)
incidents["usb_file_burst"]          = (incidents["usb_used"]   * incidents["file_burst"]            ).astype(np.float32)
incidents["after_hours_file_burst"]  = (incidents["after_hours"] * incidents["file_burst"]           ).astype(np.float32)
incidents["after_hours_email_burst"] = (incidents["after_hours"] * incidents["email_burst"]          ).astype(np.float32)
incidents["usb_external_email"]      = (incidents["usb_used"]   * incidents["external_email_burst"]  ).astype(np.float32)
incidents["after_hours_external_email"] = (incidents["after_hours"] * incidents["external_email_burst"]).astype(np.float32)

# ── Step 8: Scale hour_of_day ──
incidents["hour_of_day"] = (incidents["hour_of_day"] / 23.0).astype(np.float32)

# ── Step 9: Activity-only labeling ──
# Only label hours where suspicious activity ACTUALLY occurred
# This fixes noisy supervision from window-level labeling
incidents["label"] = 0

for _, ans in answers_df.iterrows():
    mask = (
        (incidents["user"] == ans["user"]) &
        (incidents["hour"] >= ans["start"]) &
        (incidents["hour"] <= ans["end"]) &
        (
            (incidents["usb_used"]                  == 1)  |  # USB inserted
            (incidents["file_burst"]                == 1)  |  # 20+ files/hour
            (incidents["external_email_burst"]      == 1)  |  # 3+ external emails/hour
            (incidents["after_hours_file_burst"]    == 1)  |  # file burst at night
            (incidents["usb_after_hours"]           == 1)  |  # USB at night
            (incidents["usb_external_email"]        == 1)  |  # USB + external email
            (incidents["after_hours_external_email"]== 1)  |  # external email at night
            (incidents["file_count_z"]              >  2.0)|  # unusually high file activity
            (incidents["external_email_count_z"]    >  2.0)   # unusually high external email
        )
    )
    incidents.loc[mask, "label"] = 1

incidents["label"] = incidents["label"].astype(int)

# ── Step 10: Feature columns list ──
feature_cols = [
    "logon_count_z",
    "file_count_z",
    "email_count_z",
    "http_count_z",
    "external_email_count_z",
    "usb_used",
    "after_hours",
    "rare_after_hours",
    "file_burst",
    "email_burst",
    "http_burst",
    "external_email_burst",
    "usb_after_hours",
    "usb_file_burst",
    "after_hours_file_burst",
    "after_hours_email_burst",
    "usb_external_email",
    "after_hours_external_email",
    "hour_of_day",
]
incidents[feature_cols] = incidents[feature_cols].astype(np.float32)

# ── Step 11: Diagnostics ──
print("=" * 55)
print("MERGE DIAGNOSTICS")
print("=" * 55)
mal_users = set(answers_df["user"].unique())
found_in_incidents = set(incidents["user"].unique()) & mal_users
print(f"Malicious users recovered : {len(found_in_incidents)}/{len(answers_df)}")
print(f"Total rows in incidents   : {len(incidents):,}")
print(f"Total unique users        : {incidents['user'].nunique()}")

print()
print("=" * 55)
print("LABEL DIAGNOSTICS")
print("=" * 55)
print("Label counts:")
print(incidents["label"].value_counts())
print(f"\nMalicious rate : {incidents['label'].mean():.4%}")
print(f"Malicious users with label=1: {incidents[incidents['label']==1]['user'].nunique()}")

print()
print("=" * 55)
print("DATETIME ALIGNMENT CHECK")
print("=" * 55)
sample = answers_df.iloc[0]
print(f"Sample answer  : user='{sample['user']}'  start={sample['start']}  end={sample['end']}")
print(f"Incidents hour dtype  : {incidents['hour'].dtype}")
print(f"Answers start dtype   : {answers_df['start'].dtype}")
mask_check = (
    (incidents["user"] == sample["user"]) &
    (incidents["hour"] >= sample["start"]) &
    (incidents["hour"] <= sample["end"])
)
print(f"Rows in window for '{sample['user']}' : {mask_check.sum()}")
mask_labeled = mask_check & (incidents["label"] == 1)
print(f"Rows labeled=1 for '{sample['user']}': {mask_labeled.sum()}")

print()
print("=" * 55)
print("SOURCE COVERAGE")
print("=" * 55)
for source_name, source_df in [("logon", logon), ("device", device_df)]:
    found = set(source_df["user"].unique()) & mal_users
    print(f"{source_name:8s}: {len(found)}/{len(answers_df)} malicious users")
print(f"incidents: {len(found_in_incidents)}/{len(answers_df)} malicious users")

# ── Step 12: Label distribution plot ──
import matplotlib.pyplot as plt
plt.figure(figsize=(6, 4))
incidents["label"].value_counts().sort_index().plot(kind="bar")
plt.xticks([0, 1], ["Normal", "Malicious"], rotation=0)
plt.ylabel("Count")
plt.title("Label Distribution (Activity-Only)")
plt.grid(True, axis="y")
plt.tight_layout()
plt.show()

for col in ["file_count", "email_count", "http_count", "external_email_count"]:
    plt.figure(figsize=(7,4))
    incidents.loc[incidents["label"] == 0, col].clip(upper=50).hist(alpha=0.5, bins=30, label="Normal")
    incidents.loc[incidents["label"] == 1, col].clip(upper=50).hist(alpha=0.5, bins=30, label="Malicious")
    plt.xlabel(col)
    plt.ylabel("Frequency")
    plt.title(f"{col} by Label")
    plt.legend()
    plt.grid(True)
    plt.show()

binary_cols = [
    "usb_used", "after_hours", "rare_after_hours",
    "file_burst", "email_burst", "http_burst",
    "external_email_burst", "usb_after_hours",
    "usb_file_burst", "usb_external_email"
]

rates = incidents.groupby("label")[binary_cols].mean().T
rates.columns = ["Normal", "Malicious"]

plt.figure(figsize=(8,6))
rates.plot(kind="bar")
plt.ylabel("Rate")
plt.title("Suspicious Feature Rates by Label")
plt.grid(True, axis="y")
plt.show()

timeline_df = incidents[["user", "hour", "label"] + feature_cols].copy()

user_episodes = []
for user, group in timeline_df.groupby("user"):
    group = group.sort_values("hour").reset_index(drop=True)
    if len(group) >= 3:
        user_episodes.append(group)

print("Number of user episodes:", len(user_episodes))
print("First episode length:", len(user_episodes[0]) if user_episodes else 0)

# ADD PLOTS HERE
episode_lengths = [len(ep) for ep in user_episodes]

plt.figure(figsize=(7,4))
plt.hist(episode_lengths, bins=30)
plt.xlabel("Episode Length")
plt.ylabel("Count")
plt.title("Distribution of User Episode Lengths")
plt.grid(True)
plt.show()

incidents_per_user = incidents.groupby("user").size()

print(incidents_per_user.head())

# Sort all episodes by each user's first activity timestamp (chronological order)
user_episodes_sorted = sorted(
    user_episodes,
    key=lambda ep: ep["hour"].min()
)

# 80/20 split by time — test users are the most recent 20%
split_idx = int(len(user_episodes_sorted) * 0.8)
train_episodes = user_episodes_sorted[:split_idx]
test_episodes  = user_episodes_sorted[split_idx:]

# Verify class distribution
train_labels = [1 if ep["label"].sum() > 0 else 0 for ep in train_episodes]
test_labels  = [1 if ep["label"].sum() > 0 else 0 for ep in test_episodes]

print("Train episodes:", len(train_episodes))
print("Test episodes: ", len(test_episodes))
print("\nTrain malicious rate:", pd.Series(train_labels).value_counts(normalize=True).to_dict())
print("Test malicious rate: ", pd.Series(test_labels).value_counts(normalize=True).to_dict())

train_labels = [1 if ep["label"].sum() > 0 else 0 for ep in train_episodes]
test_labels = [1 if ep["label"].sum() > 0 else 0 for ep in test_episodes]

print("Train:", pd.Series(train_labels).value_counts(normalize=True))
print("Test:", pd.Series(test_labels).value_counts(normalize=True))

!pip install gymnasium

import gymnasium as gym
from gymnasium import spaces

class CertTriageEnv(gym.Env):
    """
    Sequential RL environment over CERT user timelines.
    State = current incident features + rolling risk info
    Action affects future risk, so future states depend on actions.
    """

    def __init__(self, episodes, feature_cols, max_steps=150):
        super().__init__()
        self.episodes = episodes
        self.feature_cols = feature_cols
        self.max_steps = max_steps
        self.malicious_episodes = [ep for ep in episodes if ep["label"].sum() > 0]
        self.normal_episodes    = [ep for ep in episodes if ep["label"].sum() == 0]

        self.num_base_features = len(feature_cols)
        self.state_dim = self.num_base_features + 3

        self.action_space = spaces.Discrete(3)
        self.observation_space = spaces.Box(
            low=-np.inf, high=np.inf, shape=(self.state_dim,), dtype=np.float32
        )

        self.current_episode = None
        self.t = 0
        self.steps_this_episode = 0
        self.risk_score = 0.0
        self.prev_action = 0
        self.steps_since_escalate = 999

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)

        if len(self.malicious_episodes) > 0 and np.random.rand() < 0.70:
            self.current_episode = self.malicious_episodes[
                np.random.randint(len(self.malicious_episodes))
            ]
            mal_positions = np.where(self.current_episode["label"].values == 1)[0]
            if len(mal_positions) > 0:
                first_mal = int(mal_positions[0])
                start = max(0, first_mal - np.random.randint(5, 20))
                self.t = start
            else:
                self.t = 0
        else:
            if len(self.normal_episodes) > 0:
                self.current_episode = self.normal_episodes[
                    np.random.randint(len(self.normal_episodes))
                ]
            else:
                self.current_episode = self.episodes[np.random.randint(len(self.episodes))]
            self.t = 0

        self.steps_this_episode = 0
        self.risk_score = 0.0
        self.prev_action = 0
        self.steps_since_escalate = 999
        return self._get_state(), {}

    def _base_features(self, row):
        return row[self.feature_cols].values.astype(np.float32)

    def _get_state(self):
        row = self.current_episode.iloc[self.t]
        base = self._base_features(row)
        extra = np.array([
            self.risk_score,
            float(self.prev_action) / 2.0,
            float(min(self.steps_since_escalate, 10)) / 10.0,
        ], dtype=np.float32)
        return np.concatenate([base, extra], axis=0)

    def _behavior_risk(self, row):
        risk = 0.0
        risk += 0.10 * max(0.0, float(row["file_count_z"]))
        risk += 0.05 * max(0.0, float(row["email_count_z"]))
        risk += 0.05 * max(0.0, float(row["http_count_z"]))
        risk += 0.10 * max(0.0, float(row.get("external_email_count_z", 0.0)))
        risk += 0.30 * float(row["usb_used"])
        risk += 0.10 * float(row["after_hours"])
        risk += 0.20 * float(row.get("rare_after_hours", 0.0))
        risk += 0.25 * float(row["file_burst"])
        risk += 0.10 * float(row["email_burst"])
        risk += 0.10 * float(row["http_burst"])
        risk += 0.25 * float(row.get("external_email_burst", 0.0))
        risk += 0.40 * float(row["usb_after_hours"])
        risk += 0.50 * float(row["usb_file_burst"])
        risk += 0.30 * float(row["after_hours_file_burst"])
        risk += 0.20 * float(row["after_hours_email_burst"])
        risk += 0.60 * float(row.get("usb_external_email", 0.0))
        risk += 0.40 * float(row.get("after_hours_external_email", 0.0))
        return float(np.clip(risk, 0.0, 3.0))

    def _compute_reward(self, true_label, action, current_risk):
        if true_label == 0:
            if action == 0:   return  0.0
            elif action == 1: return -0.05
            else:             return -0.60
        else:
            if action == 2:   return  1.0
            elif action == 1: return  0.30
            else:             return -1.0

    def step(self, action):
        row = self.current_episode.iloc[self.t]
        true_label   = int(row["label"])
        current_risk = self._behavior_risk(row)
        reward       = self._compute_reward(true_label, action, current_risk)

        self.risk_score = 0.65 * self.risk_score + 0.35 * current_risk
        if current_risk < 0.15:
            self.risk_score = max(0.0, self.risk_score - 0.40)
        if action == 1:
            self.risk_score *= 0.97
        elif action == 2:
            self.risk_score *= 0.45
        self.risk_score = float(np.clip(self.risk_score, 0.0, 5.0))

        self.prev_action = action
        if action == 2:
            self.steps_since_escalate = 0
        else:
            self.steps_since_escalate += 1

        self.t += 1
        self.steps_this_episode += 1
        terminated = self.t >= len(self.current_episode)
        truncated  = self.steps_this_episode >= self.max_steps

        if terminated or truncated:
            next_state = np.zeros(self.state_dim, dtype=np.float32)
        else:
            next_state = self._get_state()

        info = {
            "true_label":           true_label,
            "risk_score":           self.risk_score,
            "user":                 row["user"],
            "time":                 row["hour"],
            "after_hours":          float(row["after_hours"]),
            "usb_used":             float(row["usb_used"]),
            "external_email_burst": float(row.get("external_email_burst", 0.0)),
            "file_burst":           float(row["file_burst"]),
            "current_risk":         float(current_risk),
        }
        return next_state, reward, terminated, truncated, info

env = CertTriageEnv(train_episodes, feature_cols, max_steps=150)
state, info = env.reset()

done = False
total_reward = 0.0
while not done:
    action = env.action_space.sample()
    next_state, reward, terminated, truncated, info = env.step(action)
    done = terminated or truncated
    total_reward += reward

print("Random episode reward:", total_reward)
print("Last step info:", info)

print("State vector shape:", state.shape)
print("State vector values:", state)
print()

# Map each value to its feature name for readability
state_feature_names = feature_cols + ["risk_score", "prev_action", "steps_since_escalate"]
print("=== State broken down by feature ===")
for name, value in zip(state_feature_names, state):
    print(f"  {name:35s} = {value:.4f}")

import random
from collections import deque
import torch
import torch.nn as nn
import torch.optim as optim

torch_device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", torch_device)

class ReplayBuffer:
    def __init__(self, capacity=50000):
        self.normal_buffer   = deque(maxlen=capacity)
        self.malicious_buffer = deque(maxlen=capacity)

    def push(self, state, action, reward, next_state, done, true_label):
        transition = (state, action, reward, next_state, done, true_label)
        if true_label == 1:
            self.malicious_buffer.append(transition)
        else:
            self.normal_buffer.append(transition)

    def sample(self, batch_size, mal_ratio=0.50):
        """Guarantee mal_ratio of every batch is malicious transitions."""
        n_mal  = min(len(self.malicious_buffer), int(batch_size * mal_ratio))
        n_norm = min(len(self.normal_buffer), batch_size - n_mal)
        # Fill remainder if one side is short
        if n_mal + n_norm < batch_size:
            extra = min(len(self.normal_buffer) - n_norm, batch_size - n_mal - n_norm)
            n_norm += max(extra, 0)

        mal_batch  = random.sample(list(self.malicious_buffer), n_mal)  if n_mal  > 0 else []
        norm_batch = random.sample(list(self.normal_buffer),    n_norm) if n_norm > 0 else []

        batch = mal_batch + norm_batch
        random.shuffle(batch)
        s, a, r, ns, d, _ = zip(*batch)

        return (
            np.array(s,  dtype=np.float32),
            np.array(a,  dtype=np.int64),
            np.array(r,  dtype=np.float32),
            np.array(ns, dtype=np.float32),
            np.array(d,  dtype=np.float32),
        )

    def __len__(self):
        return len(self.normal_buffer) + len(self.malicious_buffer)

    def counts(self):
        return {"normal": len(self.normal_buffer), "malicious": len(self.malicious_buffer), "total": len(self)}

class DQN(nn.Module):
    def __init__(self, input_dim, num_actions):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, 128),
            nn.LayerNorm(128),
            nn.ReLU(),
            nn.Linear(128, 128),
            nn.LayerNorm(128),
            nn.ReLU(),
            nn.Linear(128, num_actions),
        )

    def forward(self, x):
        return self.net(x)

state_dim = env.observation_space.shape[0]
num_actions = env.action_space.n

policy_net = DQN(state_dim, num_actions).to(torch_device)
target_net = DQN(state_dim, num_actions).to(torch_device)
target_net.load_state_dict(policy_net.state_dict())
target_net.eval()

optimizer = optim.Adam(policy_net.parameters(), lr=3e-5)
loss_fn = nn.SmoothL1Loss()

buffer = ReplayBuffer()

gamma = 0.95
batch_size = 128
num_episodes = 400
target_update_every = 15

epsilon = 1.0
epsilon_min = 0.05
epsilon_decay = 0.985

def select_action(state, eps):
    if random.random() < eps:
        return random.randrange(num_actions)
    with torch.no_grad():
        s = torch.tensor(state, dtype=torch.float32, device=torch_device).unsqueeze(0)
        q = policy_net(s)
        return int(torch.argmax(q, dim=1).item())

def optimize_model():
    if len(buffer) < 2000:
        return None

    states, actions, rewards, next_states, dones = buffer.sample(batch_size)

    states_t = torch.tensor(states, dtype=torch.float32, device=torch_device)
    actions_t = torch.tensor(actions, dtype=torch.int64, device=torch_device).unsqueeze(1)
    rewards_t = torch.tensor(rewards, dtype=torch.float32, device=torch_device).unsqueeze(1)
    next_states_t = torch.tensor(next_states, dtype=torch.float32, device=torch_device)
    dones_t = torch.tensor(dones, dtype=torch.float32, device=torch_device).unsqueeze(1)

    current_q = policy_net(states_t).gather(1, actions_t)

    with torch.no_grad():
      next_actions = policy_net(next_states_t).argmax(dim=1, keepdim=True)
      next_q = target_net(next_states_t).gather(1, next_actions)
      target_q = rewards_t + gamma * next_q * (1.0 - dones_t)

    loss = loss_fn(current_q, target_q)

    optimizer.zero_grad()
    loss.backward()
    torch.nn.utils.clip_grad_norm_(policy_net.parameters(), max_norm=10.0)  # prevent exploding gradients
    optimizer.step()

    return float(loss.item())

def evaluate_policy(env, num_eval_episodes=20):
    rows = []

    for _ in range(num_eval_episodes):
        state, info = env.reset()
        done = False

        while not done:
            action = select_action(state, eps=0.0)
            next_state, reward, terminated, truncated, info = env.step(action)
            done = terminated or truncated

            rows.append({
                "user": info["user"],
                "time": info["time"],
                "true_label": info["true_label"],
                "action": action,
                "reward": reward,
                "risk_score": info["risk_score"],
                "after_hours": info["after_hours"],
                "usb_used": info["usb_used"],
                "external_email_burst": info["external_email_burst"],
                "file_burst": info["file_burst"],
            })

            state = next_state

    return pd.DataFrame(rows)

test_env = CertTriageEnv(test_episodes, feature_cols, max_steps=150)

# NEW — added immediately after the test_env line
class EvalEnv(CertTriageEnv):
    def __init__(self, episodes, feature_cols, max_steps=150):
        super().__init__(episodes, feature_cols, max_steps)
        self._eval_idx = 0

    def reset(self, seed=None, options=None):
      gym.Env.reset(self, seed=seed)
      self.current_episode = self.episodes[self._eval_idx % len(self.episodes)]
      self._eval_idx += 1

      mal_positions = np.where(self.current_episode["label"].values == 1)[0]
      if len(mal_positions) > 0:
          first_mal = int(mal_positions[0])
          self.t = max(0, first_mal - 10)
      else:
          self.t = 0

      self.steps_this_episode = 0
      self.risk_score = 0.0
      self.prev_action = 0
      self.steps_since_escalate = 999
      return self._get_state(), {}

eval_env = EvalEnv(test_episodes, feature_cols, max_steps=150)

buffer = ReplayBuffer()

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

print("Pre-filling replay buffer with malicious transitions...")
prefill_env = CertTriageEnv(train_episodes, feature_cols, max_steps=150)

for ep in prefill_env.malicious_episodes:
    mal_positions = np.where(ep["label"].values == 1)[0]
    if len(mal_positions) == 0:
        continue

    # Walk ONLY the malicious rows directly — don't wander 30 steps
    for mal_idx in mal_positions:
        # Set env state to just before this malicious row
        prefill_env.current_episode = ep
        prefill_env.t = int(mal_idx)
        prefill_env.risk_score = 0.5   # simulate some risk already built up
        prefill_env.prev_action = 0
        prefill_env.steps_since_escalate = 10
        prefill_env.steps_this_episode = 0

        state_pf = prefill_env._get_state()

        # Try all three actions on this malicious row so agent sees reward signal
        for action_pf in [0, 1, 2]:
            # Reset to same position for each action
            prefill_env.current_episode = ep
            prefill_env.t = int(mal_idx)
            prefill_env.risk_score = 0.5
            prefill_env.steps_this_episode = 0

            state_pf = prefill_env._get_state()
            ns_pf, r_pf, term_pf, trunc_pf, info_pf = prefill_env.step(action_pf)
            buffer.push(
                state_pf, action_pf, r_pf, ns_pf,
                term_pf or trunc_pf, info_pf["true_label"]
            )

print(f"Buffer after pre-fill: {buffer.counts()}")
print("Malicious should be > normal here")

epsilon = 1.0          # hard reset so re-running cell always starts fresh

reward_history = []
epsilon_history = []
all_losses = []

for episode in range(num_episodes):
    state, info = env.reset()
    done = False
    total_reward = 0.0
    losses = []

    while not done:
        action = select_action(state, epsilon)

        next_state, reward, terminated, truncated, info = env.step(action)
        done = terminated or truncated

        buffer.push(state,action,reward,next_state,done,info["true_label"])
        loss = optimize_model()
        if loss is not None:
            losses.append(loss)
            all_losses.append(loss)

        state = next_state
        total_reward += reward

    reward_history.append(total_reward)
    epsilon = max(epsilon_min, epsilon * epsilon_decay)
    epsilon_history.append(epsilon)

    if (episode + 1) % target_update_every == 0:
        target_net.load_state_dict(policy_net.state_dict())

    if (episode + 1) % 20 == 0:
        eval_env._eval_idx = 0
        eval_rows = evaluate_policy(eval_env, num_eval_episodes=len(test_episodes))

        action_map = {0: "close", 1: "investigate", 2: "escalate"}
        eval_rows["action_name"] = eval_rows["action"].map(action_map)

        action_mix  = eval_rows["action_name"].value_counts(normalize=True)
        mal_rows    = eval_rows[eval_rows["true_label"] == 1]
        norm_rows   = eval_rows[eval_rows["true_label"] == 0]

        mal_escalated  = (mal_rows["action"] == 2).mean()  if len(mal_rows)  > 0 else 0.0
        mal_detected   = (mal_rows["action"] >= 1).mean()  if len(mal_rows)  > 0 else 0.0
        false_pos_rate = (norm_rows["action"] == 2).mean() if len(norm_rows) > 0 else 0.0

        total_escalated   = (eval_rows["action"] == 2).sum()
        correct_escalated = ((eval_rows["true_label"] == 1) & (eval_rows["action"] == 2)).sum()
        precision = correct_escalated / max(total_escalated, 1)

        print(f"\n[Diagnostic @ Episode {episode+1}]")
        print(f"Action mix: { {k: f'{v:.1%}' for k, v in action_mix.items()} }")
        print(f"Malicious  — Recall: {mal_escalated:.1%} | Detected(inv+esc): {mal_detected:.1%}")
        print(f"Normal     — False positive rate: {false_pos_rate:.1%}")
        print(f"Escalation precision: {precision:.1%}  ({correct_escalated}/{total_escalated})")

        if false_pos_rate > 0.30 and precision < 0.10:
            print("Warning: escalating everything — precision too low")
        if action_mix.get("close", 0) > 0.95 and mal_detected < 0.20:
            print("Warning: possible collapse toward close")

    print(
        f"Episode {episode+1}/{num_episodes} | "
        f"Reward={total_reward:.2f} | "
        f"AvgLoss={np.mean(losses) if losses else 0:.4f} | "
        f"Epsilon={epsilon:.3f}"
    )

# Run evaluation
eval_env._eval_idx = 0
eval_rows = evaluate_policy(eval_env, num_eval_episodes=len(test_episodes))


def rule_based_agent(results_df, threshold=0.5):
    """Simple baseline: escalate if risk score is high, else close."""
    preds = (results_df["risk_score"] > threshold).astype(int) * 2  # 2 = escalate
    mal = results_df["true_label"] == 1
    recall = ((results_df["true_label"] == 1) & (preds == 2)).sum() / mal.sum()
    fpr    = ((results_df["true_label"] == 0) & (preds == 2)).sum() / (~mal).sum()
    print(f"Rule-based baseline → Recall: {recall:.1%}, FPR: {fpr:.1%}")

rule_based_agent(eval_rows)

# Map action names (if not already done)
eval_rows["action_name"] = eval_rows["action"].map({
    0: "close",
    1: "investigate",
    2: "escalate"
})

# ---- ADD THIS BLOCK HERE ----
eval_rows["risk_bucket"] = pd.cut(
    eval_rows["risk_score"],
    bins=[0, 0.5, 1.0, 2.0, 5.0],
    labels=["low", "medium", "high", "very_high"]
)

print(pd.crosstab(eval_rows["risk_bucket"], eval_rows["action_name"], normalize="index"))

eval_rows["risk_bucket"] = pd.cut(
    eval_rows["risk_score"],
    bins=[0, 0.3, 0.6, 0.9, 2.0],
    labels=["low", "medium", "high", "very_high"]
)
print(pd.crosstab(eval_rows["risk_bucket"], eval_rows["action_name"], normalize="index"))

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.plot(reward_history)
plt.xlabel("Episode")
plt.ylabel("Total Reward")
plt.title("Training Reward Over Episodes")
plt.grid(True)
plt.show()

import numpy as np

window = 20
smoothed = np.convolve(reward_history, np.ones(window)/window, mode='valid')

plt.figure(figsize=(8,5))
plt.plot(smoothed, label="Smoothed Reward (20-episode avg)",
         linewidth=2, color="steelblue")
plt.xlabel("Episode")
plt.ylabel("Total Reward")
plt.title("Training Reward Over Episodes (Smoothed)")
plt.legend()
plt.grid(True)
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# Smooth with a 20-episode rolling average
window = 20
smoothed = np.convolve(reward_history, np.ones(window)/window, mode='valid')
episodes = np.arange(window, len(reward_history) + 1)

fig, ax = plt.subplots(figsize=(9, 4))
ax.plot(episodes, smoothed, color="#00B4D8", linewidth=2.5, label="Smoothed Reward (20-ep avg)")
ax.fill_between(episodes, smoothed, alpha=0.15, color="#00B4D8")

# Mark epsilon reaching minimum
ax.axvline(x=200, color="#F4A261", linestyle="--", linewidth=1.5, alpha=0.8, label="ε reaches 0.05")

# Annotate key points
ax.annotate("Exploration phase\nhigh variance",
            xy=(50, smoothed[30]), xytext=(30, smoothed[30] - 15),
            fontsize=9, color="#8899AA",
            arrowprops=dict(arrowstyle="->", color="#8899AA"))

ax.annotate("Policy converging",
            xy=(160, smoothed[140]), xytext=(170, smoothed[140] - 12),
            fontsize=9, color="#8899AA",
            arrowprops=dict(arrowstyle="->", color="#8899AA"))

ax.set_xlabel("Episode", fontsize=11)
ax.set_ylabel("Smoothed Reward", fontsize=11)
ax.set_title("Training Reward Over 400 Episodes (20-Episode Rolling Average)", fontsize=12)
ax.legend(fontsize=10)
ax.grid(True, alpha=0.3)
ax.set_facecolor("#162535")
fig.patch.set_facecolor("#0D1B2A")
ax.tick_params(colors="white")
ax.xaxis.label.set_color("white")
ax.yaxis.label.set_color("white")
ax.title.set_color("white")
ax.spines["bottom"].set_color("#1B6CA8")
ax.spines["left"].set_color("#1B6CA8")
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
ax.legend(facecolor="#162535", labelcolor="white", fontsize=10)

plt.tight_layout()
plt.savefig("reward_curve.png", dpi=150, bbox_inches="tight", facecolor=fig.get_facecolor())
plt.show()
print("Saved as reward_curve.png")

import numpy as np
import matplotlib.pyplot as plt

# ── Build reward_history from the actual logged values ───────────────────────
# Extract every episode reward from the training log
reward_history = [
    -9.20, -22.00, -6.65, -10.10, -1.10, -7.20, -21.35, -16.25, -9.45, -20.10,
    -15.95, -24.45, -19.80, -1.20, -4.85, -20.50, -13.75, -20.00, -2.15, -18.95,
    -15.80, 6.55, -4.65, -12.45, -15.85, -14.65, -15.50, -8.50, -20.70, -18.80,
    -3.55, -16.90, -14.65, 24.00, -2.90, -16.40, -6.35, 1.75, -16.65, 7.35,
    -4.15, 2.80, -2.35, 9.95, -8.85, -16.00, 17.70, 4.80, -6.95, -1.20,
    -3.60, -13.40, -11.50, -10.20, -10.15, -12.25, 15.05, 7.95, -11.90, -7.25,
    -6.05, -10.85, -11.90, 18.05, 29.35, 16.15, -11.05, -3.00, -12.95, -7.50,
    -13.05, -1.85, -10.30, -11.40, -18.80, -6.35, -19.00, -5.80, -12.80, -8.05,
    -9.80, -5.30, -8.85, 31.25, -8.65, -3.20, 23.15, -11.75, -2.80, -13.55,
    -2.40, -7.90, -6.75, -4.30, -0.60, -9.40, -1.90, -6.55, 1.15, 53.20,
    -9.45, -0.45, -4.70, 4.70, -6.70, -0.40, -7.30, 23.95, -4.90, 30.85,
    -29.75, -17.85, -1.00, -4.65, -2.70, -7.35, -7.55, -3.65, 45.25, -7.30,
    -4.25, -4.25, 9.35, -3.90, 26.00, -0.65, -0.70, 37.00, 2.20, -2.50,
    31.30, 0.30, -6.05, 32.95, -5.65, 3.10, 35.25, 27.05, -5.05, 1.75,
    -37.50, 0.30, 66.05, 41.40, -3.15, 28.30, -8.40, 1.25, 47.15, 2.50,
    -5.95, 2.25, -0.10, -1.20, 0.80, 0.60, -4.75, 41.40, -1.00, 3.75,
    50.50, 26.55, 55.55, -8.05, 32.20, -4.80, 0.10, -17.50, -0.60, 51.15,
    60.30, -9.15, 12.50, -2.05, -6.20, -3.15, 57.50, -3.90, 1.45, 37.45,
    1.10, -5.00, -41.70, 77.95, 36.90, 3.20, -22.90, -39.50, -9.35, -5.85,
    0.10, 70.95, 7.10, 37.30, 3.95, 12.20, 25.05, -3.05, -6.85, -10.15,
    38.40, 41.05, -4.95, 34.75, 55.60, -13.90, 0.40, -3.40, 34.15, 2.00,
    2.30, 59.95, 1.90, 4.25, -5.10, -6.85, 1.70, 1.70, -2.85, 2.85,
    29.75, -38.80, 37.45, 2.40, 63.60, -4.35, -2.20, 0.80, -0.95, -5.00,
    -2.25, -5.25, 34.65, -3.95, 78.55, 5.75, 53.25, -5.15, -3.85, -9.00,
    -6.15, 61.30, 70.50, 0.60, -4.95, -5.90, -3.00, -3.25, -6.15, 1.75,
    67.80, -5.70, 75.95, 3.45, -3.65, -3.70, -2.95, -1.45, -3.30, -2.55,
    2.15, 67.85, -19.80, 2.25, 39.20, 55.90, 70.25, -5.60, 2.55, -1.40,
    38.60, 5.70, 3.30, -24.75, -1.05, 4.00, 53.40, 38.85, 0.40, -20.75,
    7.80, 77.15, -4.20, 39.55, -4.80, -4.05, 54.80, 4.40, -3.10, -4.95,
    35.75, 58.85, 3.30, 35.00, -17.35, -2.55, 35.80, -13.05, 1.45, -9.85,
    -4.10, 32.90, 0.40, -4.50, -3.35, -0.25, -5.20, -5.30, -5.95, 2.00,
    57.50, 0.85, -4.10, -6.35, 0.65, 69.10, 4.05, 2.50, -1.10, -5.95,
    3.90, 58.05, -4.55, 3.65, -2.25, -0.15, -12.10, 0.25, -4.20, 33.55,
    -0.60, 0.10, 7.35, -6.80, -3.05, 63.20, 39.50, 2.95, 3.60, -5.35,
    -3.30, 2.20, -9.20, 1.00, 3.85, -26.80, 0.85, -4.55, 0.75, 52.40,
    1.30, 56.05, 2.50, 39.50, 2.15, -24.20, 0.70, 60.35, -3.85, -4.05,
    57.30, -6.25, 2.10, 2.45, -0.95, -4.45, -4.75, -14.60, 50.60, 35.75,
    -4.50, -3.75, -0.00, 26.95, -2.25, -5.25, 1.45, 24.65, -2.75, 56.60,
    -1.75, -2.80, -5.40, 38.20, 2.95, 3.40, -31.00, 49.65, 2.20, -3.85,
    -1.75, 4.10, -6.55, 0.85, 55.55, -4.95, 0.90, 15.50, 2.05, -2.50,
]

# ── Compute smoothed reward ───────────────────────────────────────────────────
window = 20
smoothed = np.convolve(reward_history, np.ones(window) / window, mode='valid')
# After convolution with mode='valid', result has length = 400 - 20 + 1 = 381
# Episode index starts at episode 20 and ends at episode 400
episodes = np.arange(window, len(reward_history) + 1)  # 20 to 400

# ── Plot ──────────────────────────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(9, 4))

ax.plot(episodes, smoothed, color="#00B4D8", linewidth=2.5,
        label="Smoothed Reward (20-ep avg)")
ax.fill_between(episodes, smoothed, alpha=0.15, color="#00B4D8")

# Epsilon bottoms out at episode ~198 (first time it hits 0.05)
ax.axvline(x=198, color="#F4A261", linestyle="--", linewidth=1.5,
           alpha=0.8, label="ε reaches 0.05")

# ── Annotations using actual smoothed values at correct indices ───────────────
# Index in smoothed array = episode - window
# "Exploration phase" label: point at episode 40, smoothed[20]
ep_explore = 40
idx_explore = ep_explore - window      # index 20
ax.annotate(
    "Exploration phase\nhigh variance",
    xy=(ep_explore, smoothed[idx_explore]),
    xytext=(55, smoothed[idx_explore] - 10),
    fontsize=9, color="#8899AA",
    arrowprops=dict(arrowstyle="->", color="#8899AA")
)

# "Steepest improvement" label: point at episode 120, smoothed[100]
ep_improve = 120
idx_improve = ep_improve - window      # index 100
ax.annotate(
    "Steepest improvement\n(ε dropping fast)",
    xy=(ep_improve, smoothed[idx_improve]),
    xytext=(130, smoothed[idx_improve] - 8),
    fontsize=9, color="#8899AA",
    arrowprops=dict(arrowstyle="->", color="#8899AA")
)

# "Policy converging" label: point at episode 270, smoothed[250]
ep_converge = 270
idx_converge = ep_converge - window    # index 250
ax.annotate(
    "Policy converging\n(recall ~98%)",
    xy=(ep_converge, smoothed[idx_converge]),
    xytext=(285, smoothed[idx_converge] - 9),
    fontsize=9, color="#8899AA",
    arrowprops=dict(arrowstyle="->", color="#8899AA")
)

# ── Styling ───────────────────────────────────────────────────────────────────
ax.set_xlabel("Episode", fontsize=11)
ax.set_ylabel("Smoothed Reward", fontsize=11)
ax.set_title("Training Reward Over 400 Episodes (20-Episode Rolling Average)",
             fontsize=12)
ax.set_xlim(20, 400)
ax.grid(True, alpha=0.3)
ax.set_facecolor("#162535")
fig.patch.set_facecolor("#0D1B2A")
ax.tick_params(colors="white")
ax.xaxis.label.set_color("white")
ax.yaxis.label.set_color("white")
ax.title.set_color("white")
ax.spines["bottom"].set_color("#1B6CA8")
ax.spines["left"].set_color("#1B6CA8")
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
ax.legend(facecolor="#162535", labelcolor="white", fontsize=10)

plt.tight_layout()
plt.savefig("reward_curve.png", dpi=150, bbox_inches="tight",
            facecolor=fig.get_facecolor())
plt.show()
print("Saved as reward_curve.png")

plt.figure(figsize=(8,5))
plt.plot(all_losses)
plt.xlabel("Training Steps")
plt.ylabel("Loss")
plt.title("DQN Loss Over Time")
plt.grid(True)
plt.show()

plt.figure(figsize=(8,5))
plt.plot(epsilon_history)
plt.xlabel("Episode")
plt.ylabel("Epsilon")
plt.title("Exploration Rate Over Time")
plt.grid(True)
plt.show()

window = 20
rolling_reward = pd.Series(reward_history).rolling(window).mean()

plt.figure(figsize=(8,5))
plt.plot(rolling_reward)
plt.xlabel("Episode")
plt.ylabel(f"Mean Reward (last {window})")
plt.title("Rolling Average Reward")
plt.grid(True)
plt.show()

results = evaluate_policy(eval_env, num_eval_episodes=len(test_episodes))
print(results.head(10))

# --- FAIRNESS CHECKS ---

# action groups
results["is_escalated"] = (results["action"] == 2).astype(int)
results["is_investigated_or_escalated"] = (results["action"] != 0).astype(int)

# Per-user fairness summary
user_fairness = results.groupby("user").apply(
    lambda g: pd.Series({
        "rows": len(g),
        "malicious_rate": g["true_label"].mean(),
        "escalation_rate": (g["action"] == 2).mean(),
        "investigate_or_escalate_rate": (g["action"] != 0).mean(),
        "false_positive_rate": ((g["true_label"] == 0) & (g["action"] == 2)).mean(),
        "miss_rate": ((g["true_label"] == 1) & (g["action"] == 0)).mean(),
        "avg_risk_score": g["risk_score"].mean(),
    })
).reset_index()

print("\nPer-user fairness summary:")
print(user_fairness.sort_values("false_positive_rate", ascending=False).head(10))

print("\nUsers with highest miss rates:")
print(user_fairness.sort_values("miss_rate", ascending=False).head(10))

action_map = {0: "close", 1: "investigate", 2: "escalate"}
results["action_name"] = results["action"].map(action_map)

plt.figure(figsize=(6,4))
results["action_name"].value_counts().plot(kind="bar")
plt.xlabel("Action")
plt.ylabel("Count")
plt.title("Policy Action Distribution")
plt.grid(True, axis="y")
plt.show()

ct = pd.crosstab(results["true_label"], results["action_name"])

plt.figure(figsize=(6,4))
plt.imshow(ct.values, aspect="auto")
plt.xticks(range(len(ct.columns)), ct.columns)
plt.yticks(range(len(ct.index)), ct.index.map({0: "Normal", 1: "Malicious"}))
plt.colorbar(label="Count")
plt.title("True Label vs Action")
plt.xlabel("Action")
plt.ylabel("True Label")
plt.show()

plt.figure(figsize=(7,4))
results.loc[results["true_label"] == 0, "risk_score"].hist(alpha=0.5, bins=30, label="Normal")
results.loc[results["true_label"] == 1, "risk_score"].hist(alpha=0.5, bins=30, label="Malicious")
plt.xlabel("Risk Score")
plt.ylabel("Frequency")
plt.title("Risk Score Distribution by True Label")
plt.legend()
plt.grid(True)
plt.show()

for action in ["close", "investigate", "escalate"]:
    plt.figure(figsize=(6,4))
    results.loc[results["action_name"] == action, "risk_score"].hist(bins=30)
    plt.xlabel("Risk Score")
    plt.ylabel("Frequency")
    plt.title(f"Risk Scores for Action: {action}")
    plt.grid(True)
    plt.show()

sample_user = results["user"].iloc[0]
sample = results[results["user"] == sample_user].copy()

action_map = {"close": 0, "investigate": 1, "escalate": 2}
sample["action_num"] = sample["action_name"].map(action_map)

plt.figure(figsize=(12,5))
plt.plot(sample["time"], sample["risk_score"], label="Risk Score")
plt.scatter(sample["time"], sample["true_label"], label="True Label", marker="x")
plt.scatter(sample["time"], sample["action_num"], label="Action", marker="o")
plt.xticks(rotation=45)
plt.title(f"Timeline for User {sample_user}")
plt.legend()
plt.grid(True)
plt.show()

action_names = {0: "close", 1: "investigate", 2: "escalate"}
results["action_name"] = results["action"].map(action_names)

print("Action distribution:")
print(results["action_name"].value_counts())

print("\nCross-tab:")
print(pd.crosstab(results["true_label"], results["action_name"]))

from sklearn.metrics import classification_report

normal_total = (results["true_label"] == 0).sum()
malicious_total = (results["true_label"] == 1).sum()

normal_closed = ((results["true_label"] == 0) & (results["action"] == 0)).sum()
malicious_escalated = ((results["true_label"] == 1) & (results["action"] == 2)).sum()
malicious_closed = ((results["true_label"] == 1) & (results["action"] == 0)).sum()

total_escalated = (results["action"] == 2).sum()
escalated_correct = ((results["true_label"] == 1) & (results["action"] == 2)).sum()

precision = escalated_correct / max(total_escalated, 1)
recall = escalated_correct / max(malicious_total, 1)

print("\nMetrics:")
print("normal_close_rate:", normal_closed / max(normal_total, 1))
print("malicious_escalation_rate:", malicious_escalated / max(malicious_total, 1))
print("malicious_miss_rate:", malicious_closed / max(malicious_total, 1))
print("escalation_precision:", precision)
print("escalation_recall:", recall)

y_true = results["true_label"]
y_pred = results["action"].apply(lambda x: 0 if x == 0 else 1)

print("\nBinary Detection Report (close=normal, investigate/escalate=malicious):")
print(classification_report(y_true, y_pred, target_names=["Normal", "Malicious"]))

investigation_rate = (results["action"] == 1).mean()
escalation_rate = (results["action"] == 2).mean()

print("investigation_rate:", investigation_rate)
print("escalation_rate:", escalation_rate)

# ── Plot agent behaviour for a specific malicious employee ──────────

# Pick a malicious episode from the test set
mal_test_episodes = [ep for ep in test_episodes if ep["label"].sum() > 0]
chosen_episode = mal_test_episodes[0]  # change index to see different employees

# Run the trained agent (epsilon=0) through this episode
env_single = CertTriageEnv([chosen_episode], feature_cols, max_steps=150)
state, info = env_single.reset()

steps      = []
risk_scores = []
true_labels = []
actions     = []
rewards     = []
hours       = []

done = False
while not done:
    action = select_action(state, eps=0.0)  # greedy — no random
    next_state, reward, terminated, truncated, info = env_single.step(action)
    done = terminated or truncated

    steps.append(len(steps) + 1)
    risk_scores.append(info["risk_score"])
    true_labels.append(info["true_label"])
    actions.append(action)
    rewards.append(reward)
    hours.append(info["time"])

    state = next_state

# ── Plot ────────────────────────────────────────────────────────────
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np

action_names = {0: "Close", 1: "Investigate", 2: "Escalate"}
action_colors = {0: "green", 1: "orange", 2: "red"}

fig, axes = plt.subplots(3, 1, figsize=(14, 10), sharex=True)

# Panel 1 — Rolling risk score over time
axes[0].plot(steps, risk_scores, color="steelblue", linewidth=2, label="Risk Score")
axes[0].axhline(y=1.0, color="red", linestyle="--", alpha=0.5, label="High risk threshold")
axes[0].fill_between(steps, risk_scores, alpha=0.2, color="steelblue")
axes[0].set_ylabel("Risk Score")
axes[0].set_title(f"Agent Behaviour Over Episode — User: {chosen_episode['user'].iloc[0]}")
axes[0].legend()
axes[0].grid(True, alpha=0.3)

# Shade malicious period
mal_steps = [i+1 for i, l in enumerate(true_labels) if l == 1]
if mal_steps:
    axes[0].axvspan(min(mal_steps), max(mal_steps),
                   alpha=0.15, color="red", label="Malicious period")

# Panel 2 — Agent actions at each step
action_nums = actions
colors = [action_colors[a] for a in action_nums]
axes[1].scatter(steps, action_nums, c=colors, s=60, zorder=3)
axes[1].plot(steps, action_nums, color="grey", alpha=0.3, linewidth=1)
axes[1].set_yticks([0, 1, 2])
axes[1].set_yticklabels(["Close", "Investigate", "Escalate"])
axes[1].set_ylabel("Agent Action")
axes[1].grid(True, alpha=0.3)

# Shade malicious period on action panel too
if mal_steps:
    axes[1].axvspan(min(mal_steps), max(mal_steps),
                   alpha=0.15, color="red")

# Panel 3 — Reward at each step
pos_rewards = [r if r > 0 else 0 for r in rewards]
neg_rewards = [r if r < 0 else 0 for r in rewards]
axes[2].bar(steps, pos_rewards, color="green", alpha=0.7, label="Positive reward")
axes[2].bar(steps, neg_rewards, color="red", alpha=0.7, label="Negative reward")
axes[2].axhline(y=0, color="black", linewidth=0.5)
axes[2].set_ylabel("Reward")
axes[2].set_xlabel("Step")
axes[2].legend()
axes[2].grid(True, alpha=0.3)

if mal_steps:
    axes[2].axvspan(min(mal_steps), max(mal_steps),
                   alpha=0.15, color="red")

# Legend for action colors
patches = [mpatches.Patch(color=c, label=action_names[a])
           for a, c in action_colors.items()]
axes[1].legend(handles=patches, loc="upper right")

plt.tight_layout()
plt.show()

# Print summary
print(f"\n=== Episode Summary for {chosen_episode['user'].iloc[0]} ===")
print(f"Total steps:          {len(steps)}")
print(f"Malicious steps:      {sum(true_labels)}")
print(f"Close decisions:      {actions.count(0)} ({actions.count(0)/len(actions)*100:.1f}%)")
print(f"Investigate decisions:{actions.count(1)} ({actions.count(1)/len(actions)*100:.1f}%)")
print(f"Escalate decisions:   {actions.count(2)} ({actions.count(2)/len(actions)*100:.1f}%)")
print(f"Total reward:         {sum(rewards):.2f}")
print(f"Correct escalations:  {sum(1 for a,l in zip(actions,true_labels) if a==2 and l==1)}")
print(f"False alarms:         {sum(1 for a,l in zip(actions,true_labels) if a==2 and l==0)}")
print(f"Missed threats:       {sum(1 for a,l in zip(actions,true_labels) if a==0 and l==1)}")

# =========================
# SARSA TRAINING + EVALUATION
# =========================

import random
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.optim as optim

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
)

warnings.filterwarnings("ignore", category=DeprecationWarning)

# ---------------------------------
# Device
# ---------------------------------
torch_device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", torch_device)

# ---------------------------------
# Q-network for SARSA
# ---------------------------------
class SARSAQNetwork(nn.Module):
    def __init__(self, input_dim, num_actions):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, 128),
            nn.LayerNorm(128),
            nn.ReLU(),
            nn.Linear(128, 128),
            nn.LayerNorm(128),
            nn.ReLU(),
            nn.Linear(128, num_actions),
        )

    def forward(self, x):
        return self.net(x)

# ---------------------------------
# Build environments
# ---------------------------------
train_env = CertTriageEnv(train_episodes, feature_cols, max_steps=150)
eval_env = EvalEnv(test_episodes, feature_cols, max_steps=150)

state_dim = train_env.observation_space.shape[0]
num_actions = train_env.action_space.n

sarsa_net = SARSAQNetwork(state_dim, num_actions).to(torch_device)
optimizer = optim.Adam(sarsa_net.parameters(), lr=1e-4)
loss_fn = nn.SmoothL1Loss()

# ---------------------------------
# Hyperparameters
# ---------------------------------
gamma = 0.95
num_episodes = 400

epsilon = 1.0
epsilon_min = 0.05
epsilon_decay = 0.985

# Optional: slightly slower decay if learning is unstable
# epsilon_decay = 0.990

# ---------------------------------
# Action selection
# ---------------------------------
def sarsa_select_action(state, eps):
    if random.random() < eps:
        return random.randrange(num_actions)

    with torch.no_grad():
        s = torch.tensor(state, dtype=torch.float32, device=torch_device).unsqueeze(0)
        q_values = sarsa_net(s)
        return int(torch.argmax(q_values, dim=1).item())

# ---------------------------------
# Single SARSA update
# ---------------------------------
def sarsa_update(state, action, reward, next_state, next_action, done):
    """
    SARSA target:
        target = r + gamma * Q(s', a')   if not done
               = r                       if done
    """
    state_t = torch.tensor(state, dtype=torch.float32, device=torch_device).unsqueeze(0)
    next_state_t = torch.tensor(next_state, dtype=torch.float32, device=torch_device).unsqueeze(0)

    action_t = torch.tensor([[action]], dtype=torch.int64, device=torch_device)
    reward_t = torch.tensor([[reward]], dtype=torch.float32, device=torch_device)

    current_q = sarsa_net(state_t).gather(1, action_t)

    with torch.no_grad():
        if done:
            target_q = reward_t
        else:
            next_action_t = torch.tensor([[next_action]], dtype=torch.int64, device=torch_device)
            next_q = sarsa_net(next_state_t).gather(1, next_action_t)
            target_q = reward_t + gamma * next_q

    loss = loss_fn(current_q, target_q)

    optimizer.zero_grad()
    loss.backward()
    torch.nn.utils.clip_grad_norm_(sarsa_net.parameters(), max_norm=10.0)
    optimizer.step()

    return float(loss.item())

# ---------------------------------
# Detailed policy evaluation
# ---------------------------------
def evaluate_sarsa_policy(env, num_eval_episodes=None, eps=0.0):
    """
    Runs greedy evaluation by default (eps=0.0) and returns:
    1) step-level dataframe
    2) episode-level dataframe
    """
    if num_eval_episodes is None:
        num_eval_episodes = len(env.episodes)

    step_rows = []
    episode_rows = []

    for ep_idx in range(num_eval_episodes):
        state, info = env.reset()
        done = False

        ep_reward = 0.0
        ep_len = 0
        ep_actions = []
        ep_labels = []
        ep_risks = []

        while not done:
            action = sarsa_select_action(state, eps=eps)
            next_state, reward, terminated, truncated, info = env.step(action)
            done = terminated or truncated

            ep_reward += reward
            ep_len += 1
            ep_actions.append(action)
            ep_labels.append(info["true_label"])
            ep_risks.append(info["risk_score"])

            step_rows.append({
                "episode_id": ep_idx,
                "user": info["user"],
                "time": info["time"],
                "true_label": int(info["true_label"]),
                "action": int(action),
                "reward": float(reward),
                "risk_score": float(info["risk_score"]),
                "after_hours": float(info["after_hours"]),
                "usb_used": float(info["usb_used"]),
                "external_email_burst": float(info["external_email_burst"]),
                "file_burst": float(info["file_burst"]),
                "current_risk": float(info["current_risk"]),
                "done": int(done),
            })

            state = next_state

        episode_rows.append({
            "episode_id": ep_idx,
            "user": step_rows[-1]["user"] if len(step_rows) > 0 else None,
            "episode_length": ep_len,
            "episode_reward": ep_reward,
            "malicious_steps": int(np.sum(ep_labels)),
            "normal_steps": int(len(ep_labels) - np.sum(ep_labels)),
            "close_rate": float(np.mean(np.array(ep_actions) == 0)) if ep_actions else 0.0,
            "investigate_rate": float(np.mean(np.array(ep_actions) == 1)) if ep_actions else 0.0,
            "escalate_rate": float(np.mean(np.array(ep_actions) == 2)) if ep_actions else 0.0,
            "avg_risk_score": float(np.mean(ep_risks)) if ep_risks else 0.0,
            "max_risk_score": float(np.max(ep_risks)) if ep_risks else 0.0,
            "had_any_malicious": int(np.sum(ep_labels) > 0),
            "detected_any_malicious": int(
                np.any((np.array(ep_labels) == 1) & (np.array(ep_actions) >= 1))
            ) if ep_actions else 0,
            "escalated_any_malicious": int(
                np.any((np.array(ep_labels) == 1) & (np.array(ep_actions) == 2))
            ) if ep_actions else 0,
        })

    steps_df = pd.DataFrame(step_rows)
    episodes_df = pd.DataFrame(episode_rows)

    return steps_df, episodes_df

# ---------------------------------
# Metrics computation
# ---------------------------------
def compute_sarsa_metrics(results_df):
    """
    We will measure:
    - binary detection (close=0 => normal, investigate/escalate => suspicious)
    - escalation quality
    - action distribution
    - fairness / per-user behavior
    """
    results = results_df.copy()

    results["action_name"] = results["action"].map({
        0: "close",
        1: "investigate",
        2: "escalate"
    })

    # Binary detection view:
    # close -> predicted normal
    # investigate/escalate -> predicted suspicious
    y_true = results["true_label"].astype(int).values
    y_pred_binary = (results["action"] != 0).astype(int).values
    y_pred_escalate = (results["action"] == 2).astype(int).values

    metrics = {}

    # Action mix
    action_mix = results["action_name"].value_counts(normalize=True).to_dict()
    metrics["action_mix"] = action_mix

    # Main triage metrics
    malicious_rows = results[results["true_label"] == 1]
    normal_rows = results[results["true_label"] == 0]

    metrics["malicious_detect_rate"] = float((malicious_rows["action"] >= 1).mean()) if len(malicious_rows) else 0.0
    metrics["malicious_escalation_rate"] = float((malicious_rows["action"] == 2).mean()) if len(malicious_rows) else 0.0
    metrics["malicious_miss_rate"] = float((malicious_rows["action"] == 0).mean()) if len(malicious_rows) else 0.0
    metrics["normal_close_rate"] = float((normal_rows["action"] == 0).mean()) if len(normal_rows) else 0.0
    metrics["false_positive_escalation_rate"] = float((normal_rows["action"] == 2).mean()) if len(normal_rows) else 0.0
    metrics["false_positive_detect_rate"] = float((normal_rows["action"] >= 1).mean()) if len(normal_rows) else 0.0

    # Escalation precision/recall
    total_escalated = int((results["action"] == 2).sum())
    correct_escalated = int(((results["true_label"] == 1) & (results["action"] == 2)).sum())
    total_malicious = int((results["true_label"] == 1).sum())

    metrics["escalation_precision"] = correct_escalated / max(total_escalated, 1)
    metrics["escalation_recall"] = correct_escalated / max(total_malicious, 1)

    # Binary detection metrics
    metrics["binary_precision"] = float(precision_score(y_true, y_pred_binary, zero_division=0))
    metrics["binary_recall"] = float(recall_score(y_true, y_pred_binary, zero_division=0))
    metrics["binary_f1"] = float(f1_score(y_true, y_pred_binary, zero_division=0))

    # Escalation as positive class
    metrics["escalation_as_positive_precision"] = float(precision_score(y_true, y_pred_escalate, zero_division=0))
    metrics["escalation_as_positive_recall"] = float(recall_score(y_true, y_pred_escalate, zero_division=0))
    metrics["escalation_as_positive_f1"] = float(f1_score(y_true, y_pred_escalate, zero_division=0))

    # AUC using risk score if both classes present
    if len(np.unique(y_true)) == 2:
        metrics["risk_score_auc"] = float(roc_auc_score(y_true, results["risk_score"].values))
    else:
        metrics["risk_score_auc"] = np.nan

    # Confusion matrices
    metrics["binary_confusion_matrix"] = confusion_matrix(y_true, y_pred_binary).tolist()
    metrics["escalation_confusion_matrix"] = confusion_matrix(y_true, y_pred_escalate).tolist()

    # Per-user fairness style summary
    user_fairness = results.groupby("user").apply(
        lambda g: pd.Series({
            "rows": len(g),
            "malicious_rate": g["true_label"].mean(),
            "escalation_rate": (g["action"] == 2).mean(),
            "investigate_or_escalate_rate": (g["action"] != 0).mean(),
            "false_positive_rate": ((g["true_label"] == 0) & (g["action"] == 2)).mean(),
            "miss_rate": ((g["true_label"] == 1) & (g["action"] == 0)).mean(),
            "avg_risk_score": g["risk_score"].mean(),
        })
    ).reset_index()

    return metrics, user_fairness

# ---------------------------------
# Plotting helper
# ---------------------------------
def plot_sarsa_training_curves(reward_history, epsilon_history, loss_history):
    plt.figure(figsize=(8, 5))
    plt.plot(reward_history)
    plt.xlabel("Episode")
    plt.ylabel("Total Reward")
    plt.title("SARSA Training Reward")
    plt.grid(True)
    plt.show()

    if len(reward_history) >= 20:
        rolling_reward = pd.Series(reward_history).rolling(20).mean()
        plt.figure(figsize=(8, 5))
        plt.plot(rolling_reward)
        plt.xlabel("Episode")
        plt.ylabel("Rolling Mean Reward (20)")
        plt.title("SARSA Rolling Reward")
        plt.grid(True)
        plt.show()

    plt.figure(figsize=(8, 5))
    plt.plot(loss_history)
    plt.xlabel("Training Steps")
    plt.ylabel("Loss")
    plt.title("SARSA TD Loss")
    plt.grid(True)
    plt.show()

    plt.figure(figsize=(8, 5))
    plt.plot(epsilon_history)
    plt.xlabel("Episode")
    plt.ylabel("Epsilon")
    plt.title("SARSA Exploration Rate")
    plt.grid(True)
    plt.show()

# ---------------------------------
# Evaluation plots
# ---------------------------------
def plot_sarsa_evaluation(results_df, user_fairness_df):
    results = results_df.copy()
    results["action_name"] = results["action"].map({
        0: "close",
        1: "investigate",
        2: "escalate"
    })

    # Action distribution
    plt.figure(figsize=(6, 4))
    results["action_name"].value_counts().plot(kind="bar")
    plt.xlabel("Action")
    plt.ylabel("Count")
    plt.title("SARSA Policy Action Distribution")
    plt.grid(True, axis="y")
    plt.show()

    # Label vs action
    ct = pd.crosstab(results["true_label"], results["action_name"])
    print("\nTrue Label vs Action:")
    print(ct)

    plt.figure(figsize=(6, 4))
    plt.imshow(ct.values, aspect="auto")
    plt.xticks(range(len(ct.columns)), ct.columns)
    plt.yticks(range(len(ct.index)), ["Normal" if i == 0 else "Malicious" for i in ct.index])
    plt.colorbar(label="Count")
    plt.title("True Label vs Action")
    plt.xlabel("Action")
    plt.ylabel("True Label")
    plt.show()

    # Risk score by true label
    plt.figure(figsize=(7, 4))
    results.loc[results["true_label"] == 0, "risk_score"].hist(alpha=0.5, bins=30, label="Normal")
    results.loc[results["true_label"] == 1, "risk_score"].hist(alpha=0.5, bins=30, label="Malicious")
    plt.xlabel("Risk Score")
    plt.ylabel("Frequency")
    plt.title("Risk Score Distribution by True Label")
    plt.legend()
    plt.grid(True)
    plt.show()

    # Risk bucket vs action
    results["risk_bucket"] = pd.cut(
        results["risk_score"],
        bins=[0, 0.3, 0.6, 0.9, 2.0, 5.0],
        labels=["low", "medium", "high", "very_high", "extreme"],
        include_lowest=True
    )
    rb = pd.crosstab(results["risk_bucket"], results["action_name"], normalize="index")
    print("\nRisk bucket vs action:")
    print(rb)

    # Per-user fairness view
    plt.figure(figsize=(8, 5))
    plt.hist(user_fairness_df["false_positive_rate"], bins=25)
    plt.xlabel("Per-user false positive escalation rate")
    plt.ylabel("Number of users")
    plt.title("Fairness Check: User-level False Positive Rates")
    plt.grid(True)
    plt.show()

    plt.figure(figsize=(8, 5))
    plt.hist(user_fairness_df["miss_rate"], bins=25)
    plt.xlabel("Per-user miss rate")
    plt.ylabel("Number of users")
    plt.title("Fairness Check: User-level Miss Rates")
    plt.grid(True)
    plt.show()

# ---------------------------------
# Episode timeline plot
# ---------------------------------
def plot_single_episode_timeline(env, episode_index=0):
    """
    Visualize one chosen evaluation episode
    """
    chosen_episode = env.episodes[episode_index]
    single_env = CertTriageEnv([chosen_episode], feature_cols, max_steps=150)

    state, info = single_env.reset()
    done = False

    steps = []
    risks = []
    labels = []
    actions = []
    rewards = []
    times = []

    step_no = 0
    while not done:
        action = sarsa_select_action(state, eps=0.0)
        next_state, reward, terminated, truncated, info = single_env.step(action)
        done = terminated or truncated

        step_no += 1
        steps.append(step_no)
        risks.append(info["risk_score"])
        labels.append(info["true_label"])
        actions.append(action)
        rewards.append(reward)
        times.append(info["time"])

        state = next_state

    action_names = {0: "Close", 1: "Investigate", 2: "Escalate"}
    action_colors = {0: "green", 1: "orange", 2: "red"}

    import matplotlib.patches as mpatches

    fig, axes = plt.subplots(3, 1, figsize=(14, 10), sharex=True)

    axes[0].plot(steps, risks, linewidth=2)
    axes[0].axhline(y=1.0, linestyle="--", alpha=0.5)
    axes[0].fill_between(steps, risks, alpha=0.2)
    axes[0].set_ylabel("Risk Score")
    axes[0].set_title(f"SARSA Episode Timeline — User: {chosen_episode['user'].iloc[0]}")
    axes[0].grid(True, alpha=0.3)

    mal_steps = [i + 1 for i, l in enumerate(labels) if l == 1]
    if mal_steps:
        axes[0].axvspan(min(mal_steps), max(mal_steps), alpha=0.15)

    colors = [action_colors[a] for a in actions]
    axes[1].scatter(steps, actions, c=colors, s=60, zorder=3)
    axes[1].plot(steps, actions, alpha=0.3, linewidth=1)
    axes[1].set_yticks([0, 1, 2])
    axes[1].set_yticklabels(["Close", "Investigate", "Escalate"])
    axes[1].set_ylabel("Action")
    axes[1].grid(True, alpha=0.3)

    if mal_steps:
        axes[1].axvspan(min(mal_steps), max(mal_steps), alpha=0.15)

    pos_rewards = [r if r > 0 else 0 for r in rewards]
    neg_rewards = [r if r < 0 else 0 for r in rewards]
    axes[2].bar(steps, pos_rewards, alpha=0.7, label="Positive reward")
    axes[2].bar(steps, neg_rewards, alpha=0.7, label="Negative reward")
    axes[2].axhline(y=0, linewidth=0.5)
    axes[2].set_ylabel("Reward")
    axes[2].set_xlabel("Step")
    axes[2].legend()
    axes[2].grid(True, alpha=0.3)

    if mal_steps:
        axes[2].axvspan(min(mal_steps), max(mal_steps), alpha=0.15)

    patches = [mpatches.Patch(color=c, label=action_names[a]) for a, c in action_colors.items()]
    axes[1].legend(handles=patches, loc="upper right")

    plt.tight_layout()
    plt.show()

    print(f"\n=== Episode Summary for {chosen_episode['user'].iloc[0]} ===")
    print(f"Total steps: {len(steps)}")
    print(f"Malicious steps: {sum(labels)}")
    print(f"Close decisions: {actions.count(0)} ({actions.count(0)/len(actions)*100:.1f}%)")
    print(f"Investigate decisions: {actions.count(1)} ({actions.count(1)/len(actions)*100:.1f}%)")
    print(f"Escalate decisions: {actions.count(2)} ({actions.count(2)/len(actions)*100:.1f}%)")
    print(f"Total reward: {sum(rewards):.2f}")
    print(f"Correct escalations: {sum(1 for a, l in zip(actions, labels) if a == 2 and l == 1)}")
    print(f"False alarms: {sum(1 for a, l in zip(actions, labels) if a == 2 and l == 0)}")
    print(f"Missed threats: {sum(1 for a, l in zip(actions, labels) if a == 0 and l == 1)}")

# ---------------------------------
# TRAIN SARSA
# ---------------------------------
reward_history = []
epsilon_history = []
loss_history = []

for episode in range(num_episodes):
    state, info = train_env.reset()
    action = sarsa_select_action(state, epsilon)
    done = False

    total_reward = 0.0
    episode_losses = []

    while not done:
        next_state, reward, terminated, truncated, info = train_env.step(action)
        done = terminated or truncated

        if not done:
            next_action = sarsa_select_action(next_state, epsilon)
        else:
            next_action = 0  # dummy, unused in terminal update

        loss = sarsa_update(
            state=state,
            action=action,
            reward=reward,
            next_state=next_state,
            next_action=next_action,
            done=done
        )

        episode_losses.append(loss)
        loss_history.append(loss)

        state = next_state
        action = next_action
        total_reward += reward

    reward_history.append(total_reward)
    epsilon = max(epsilon_min, epsilon * epsilon_decay)
    epsilon_history.append(epsilon)

    if (episode + 1) % 20 == 0:
        eval_env._eval_idx = 0
        interim_steps, _ = evaluate_sarsa_policy(
            eval_env,
            num_eval_episodes=len(test_episodes),
            eps=0.0
        )
        interim_metrics, _ = compute_sarsa_metrics(interim_steps)

        print(f"\n[Evaluation at Episode {episode+1}]")
        print("Action mix:", {k: f"{v:.1%}" for k, v in interim_metrics["action_mix"].items()})
        print(f"Malicious detect rate: {interim_metrics['malicious_detect_rate']:.3f}")
        print(f"Malicious escalation rate: {interim_metrics['malicious_escalation_rate']:.3f}")
        print(f"Malicious miss rate: {interim_metrics['malicious_miss_rate']:.3f}")
        print(f"Normal close rate: {interim_metrics['normal_close_rate']:.3f}")
        print(f"False positive escalation rate: {interim_metrics['false_positive_escalation_rate']:.3f}")
        print(f"Escalation precision: {interim_metrics['escalation_precision']:.3f}")
        print(f"Escalation recall: {interim_metrics['escalation_recall']:.3f}")
        print(f"Binary F1: {interim_metrics['binary_f1']:.3f}")

    print(
        f"Episode {episode+1}/{num_episodes} | "
        f"Reward={total_reward:.2f} | "
        f"AvgLoss={np.mean(episode_losses):.4f} | "
        f"Epsilon={epsilon:.3f}"
    )

# ---------------------------------
# FINAL EVALUATION
# ---------------------------------
eval_env._eval_idx = 0
results_df, episode_summary_df = evaluate_sarsa_policy(
    eval_env,
    num_eval_episodes=len(test_episodes),
    eps=0.0
)

metrics, user_fairness_df = compute_sarsa_metrics(results_df)

print("\n================ FINAL SARSA EVALUATION ================\n")

for k, v in metrics.items():
    if isinstance(v, float):
        print(f"{k}: {v:.4f}")
    else:
        print(f"{k}: {v}")

print("\nBinary Detection Report (close=normal, investigate/escalate=suspicious):")
y_true = results_df["true_label"].astype(int)
y_pred_binary = (results_df["action"] != 0).astype(int)
print(classification_report(y_true, y_pred_binary, target_names=["Normal", "Malicious"], zero_division=0))

print("\nTop users by false positive rate:")
print(user_fairness_df.sort_values("false_positive_rate", ascending=False).head(10))

print("\nTop users by miss rate:")
print(user_fairness_df.sort_values("miss_rate", ascending=False).head(10))

print("\nEpisode-level summary sample:")
print(episode_summary_df.head(10))

# ---------------------------------
# PLOTS
# ---------------------------------
plot_sarsa_training_curves(reward_history, epsilon_history, loss_history)
plot_sarsa_evaluation(results_df, user_fairness_df)

# Plot one malicious episode if available
mal_eval_indices = []
for i, ep in enumerate(eval_env.episodes):
    if ep["label"].sum() > 0:
        mal_eval_indices.append(i)

if len(mal_eval_indices) > 0:
    plot_single_episode_timeline(eval_env, episode_index=mal_eval_indices[0])
else:
    print("No malicious episode found in evaluation set.")